language: rust
cache: cargo

matrix:
  include:
  - rust: stable
    script:
    - cargo test
  - rust: nightly-2018-12-04
    before_script:
    - rustup component add rustfmt-preview
    script:
    - cargo test
    - cargo fmt --all -- --check
  # Test if crate can be truly built without std
  - rust: nightly
    env: TARGET=thumbv7em-none-eabi
    script: xargo build --no-default-features --features="nightly" --target $TARGET
    install:
      - cargo install xargo || true
      - rustup target install armv7-unknown-linux-gnueabihf
      - rustup component add rust-src

notifications:
  slack:
    rooms:
      - dalek-cryptography:Xxv9WotKYWdSoKlgKNqXiHoD#dalek-bots
