language: rust
cache: cargo


matrix:
  include:
  - rust: stable
    script:
    - cargo test
  - rust: nightly-2018-12-04
    before_script:
    - rustup component add rustfmt-preview
    script:
    - cargo test
    - cargo fmt --all -- --check
  # Test if crate can be truly built without std, cargo-nono 0.1.5 now works against clear_on_drop
  - rust: nightly
    script:
      - cargo nono check --no-default-features
    install:
      - cargo install cargo-nono || true

notifications:
  slack:
    rooms:
      - dalek-cryptography:Xxv9WotKYWdSoKlgKNqXiHoD#dalek-bots
